import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import type { CheckReport } from "../src/check.ts";
import { loadTypeScript } from "../src/typescript.ts";
import { CAMPAIGNS, cli, contract, copyFixture, data, designProject, editFile, find, generated, inFixture, isError, MAIL, mdx, QUOTA, senderWarning, snapshot, summary, writeFile } from "./helpers.ts";

function check(root: string, ...args: string[]): { code: number; report: CheckReport } {
  const { code, stdout, stderr } = cli(root, "check", "--phase", "design", "--format", "json", ...args);
  assert.equal(stderr, "");
  return { code, report: JSON.parse(stdout) };
}

const repository = path.join(import.meta.dirname, "..");

/** Gives a project its own `typescript` package: the TypeScript 5 that the repository installs for these tests. */
function installTypeScript5(root: string): void {
  fs.mkdirSync(path.join(root, "node_modules"), { recursive: true });
  fs.symlinkSync(path.join(repository, "node_modules/typescript-5"), path.join(root, "node_modules/typescript"));
}

test("check --phase design reports the plan fixture: 3 contracts, 1 data type, 8 invariants, one warning", (t) => {
  const root = copyFixture(t, "vertical");
  const before = snapshot(root);

  const { code, report } = check(root);
  assert.equal(code, 0);
  assert.deepEqual(report, {
    schemaVersion: 1,
    command: "check",
    phase: "design",
    ok: true,
    scope: { tsconfig: "tsconfig.json", designFiles: [CAMPAIGNS, MAIL, QUOTA], typescript: { version: "6.0.3", source: "project" } },
    // This phase does not look at generated files, implementations or tests: "not checked" is not "none".
    generatedArtifacts: [CAMPAIGNS, MAIL, QUOTA].map((source) => ({ source, file: generated(source), status: "not-checked" })),
    counts: { contracts: 3, data: 1, invariants: 8, implementations: null, testDeclarations: null, linkedInvariants: null },
    invariants: [
      { contract: "Send", id: "quota", member: "run", linkedTestCount: null },
      { contract: "Send", id: "limit", member: "run", linkedTestCount: null },
      { contract: "Send", id: "quota-error", member: "run", linkedTestCount: null },
      { contract: "Send", id: "sender-error", member: "run", linkedTestCount: null },
      { contract: "Quota", id: "accounts", member: null, linkedTestCount: null },
      { contract: "Quota", id: "empty", member: "take", linkedTestCount: null },
      { contract: "Quota", id: "consume", member: "take", linkedTestCount: null },
      { contract: "Quota", id: "race", member: "take", linkedTestCount: null },
    ],
    diagnostics: [
      {
        code: "W_NO_INVARIANTS",
        severity: "warning",
        message: 'Contract "Sender" has no `@invariant`: only its types can be checked.',
        ...inFixture(MAIL, "Sender {"),
        contract: "Sender",
      },
    ],
  });
  assert.deepEqual(snapshot(root), before);

  assert.equal(
    cli(root, "check", "--phase", "design").stdout,
    [
      senderWarning(),
      "check --phase design: 3 designs, 3 contracts, 1 data type, 8 invariants; 0 errors, 1 warning. TypeScript 6.0.3 (project).",
      "",
    ].join("\n"),
  );
});

test("the design phase ignores generated files: missing, current or stale, the report is the same", (t) => {
  const root = copyFixture(t, "vertical");
  const missing = check(root);
  assert.equal(cli(root, "extract").code, 0);
  assert.deepEqual(check(root), missing);

  writeFile(root, generated(QUOTA), "// @generated by design; DO NOT EDIT.\n// Source: design.mdx\n\nexport type AccountId = never;\n");
  assert.deepEqual(check(root), missing);
});

test("errors are exit 1 and warnings exit 0; a diagnostic names its contract and invariant", (t) => {
  const root = copyFixture(t, "vertical");
  const original = inFixture(QUOTA, "@invariant empty");
  const duplicate = inFixture(QUOTA, "@invariant consume");
  editFile(root, QUOTA, (s) => s.replace("@invariant consume", "@invariant empty"));

  const { code, report } = check(root);
  assert.equal(code, 1);
  assert.equal(report.ok, false);
  assert.deepEqual(
    report.diagnostics.filter(isError).map(({ code, contract, invariant, line }) => ({ code, contract, invariant, line })),
    [{ code: "E_INVARIANT_DUPLICATE", contract: "Quota", invariant: "empty", line: duplicate.line }],
  );
  assert.equal(report.counts.invariants, 7);

  const text = cli(root, "check", "--phase", "design");
  assert.equal(text.code, 1);
  assert.ok(
    text.stdout.includes(
      `${QUOTA}:${duplicate.line}:${duplicate.column}: error E_INVARIANT_DUPLICATE: Invariant id "empty" is already used in contract "Quota".\n` +
        `  ${QUOTA}:${original.line}:${original.column}: The other invariant.\n`,
    ),
  );
  assert.match(text.stdout, /7 invariants; 1 error, 1 warning\./);
});

test("configuration and environment problems are exit 2, an empty scope exit 1", (t) => {
  const root = copyFixture(t, "vertical");
  const codes = (args: string[] = []) => {
    const { code, report } = check(root, ...args);
    return { code, ok: report.ok, diagnostics: report.diagnostics.map((diagnostic) => diagnostic.code), counts: report.counts, invariants: report.invariants };
  };
  // Nothing was indexed: the counts are unknown, which is not zero.
  const unknown = { counts: { contracts: null, data: null, invariants: null, implementations: null, testDeclarations: null, linkedInvariants: null }, invariants: null };

  assert.deepEqual(codes(["--config", "nope.json"]), { code: 2, ok: false, diagnostics: ["E_CONFIG"], ...unknown });
  writeFile(root, ".design/config.json", '{ "version": 1, "tsconfig": "missing.json" }');
  assert.deepEqual(codes(), { code: 2, ok: false, diagnostics: ["E_ENVIRONMENT"], ...unknown });
  assert.match(cli(root, "check", "--phase", "design").stdout, /check --phase design: 3 designs, contracts not indexed; 1 error, 0 warnings\./);
  writeFile(root, ".design/config.json", '{ "version": 1, "designs": ["lib/**/.design/design.mdx"] }');
  assert.deepEqual(codes(), { code: 1, ok: false, diagnostics: ["E_NO_DESIGNS"], ...unknown });
});

test("reports are deterministic", (t) => {
  const root = copyFixture(t, "vertical");
  editFile(root, MAIL, (s) => s.replace("send(text: string)", "send(text: Txt)"));
  const run = () => cli(root, "check", "--phase", "design", "--format", "json").stdout;
  assert.equal(run(), run());
});

test("the project's own TypeScript checks its designs", (t) => {
  // Without `types`, TypeScript 5 loads every @types package and TypeScript 6 loads none.
  const designs = { a: mdx(data("Bytes", "Buffer"), contract("Thing")) };

  // This project has no TypeScript of its own; the nearest one is the repository's TypeScript 6.
  const newer = check(designProject(t, designs));
  assert.deepEqual(newer.report.scope.typescript, { version: "6.0.3", source: "project" });
  assert.deepEqual(
    newer.report.diagnostics.filter(isError).map(({ code, tsCode }) => ({ code, tsCode })),
    [{ code: "E_TYPESCRIPT", tsCode: 2591 }],
  );

  const root = designProject(t, designs);
  installTypeScript5(root);
  const own = check(root);
  assert.deepEqual(own.report.scope.typescript, { version: "5.9.3", source: "project" });
  assert.deepEqual(own.report.diagnostics.filter(isError), []);
  assert.equal(own.code, 0);
});

test("TypeScript 5 accepts what it does not deprecate, and the plan fixture", (t) => {
  const root = copyFixture(t, "vertical");
  installTypeScript5(root);
  editFile(root, "tsconfig.json", (s) => s.replace('"strict": true,', '"strict": true,\n    "baseUrl": ".",'));

  const { code, report } = check(root);
  assert.equal(code, 0);
  assert.deepEqual(report.scope.typescript, { version: "5.9.3", source: "project" });
  assert.deepEqual(report.counts, { contracts: 3, data: 1, invariants: 8, implementations: null, testDeclarations: null, linkedInvariants: null });

  const text = editFile(root, QUOTA, (s) => s.replace("take(accountId: AccountId)", "take(accountId: AccountIdd)"));
  assert.deepEqual(
    check(root).report.diagnostics.filter(isError).map(summary),
    [{ code: "E_TYPESCRIPT", tsCode: 2552, file: QUOTA, ...find(text, "AccountIdd") }],
  );
});

test("without a usable TypeScript in the project the bundled one is used", (t) => {
  // Outside the repository, so that no `typescript` package is found above the project.
  const root = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  assert.deepEqual(loadTypeScript(root).info, { version: "6.0.3", source: "bundled" });

  // TypeScript 7 ships no compiler API under its main entry, only a version.
  writeFile(root, "node_modules/typescript/package.json", JSON.stringify({ name: "typescript", version: "7.0.2", main: "index.js" }));
  writeFile(root, "node_modules/typescript/index.js", 'module.exports = { version: "7.0.2" };\n');
  assert.deepEqual(loadTypeScript(root).info, { version: "6.0.3", source: "bundled", fallbackReason: "the project's TypeScript 7.0.2 has no usable compiler API" });

  writeFile(root, "package.json", JSON.stringify({ private: true, type: "module" }));
  writeFile(root, "tsconfig.json", JSON.stringify({ compilerOptions: { module: "NodeNext", strict: true, noEmit: true } }));
  writeFile(root, "src/a/.design/design.mdx", mdx(contract("Thing", "run(): void;", "@invariant ok Працює.")));
  const text = cli(root, "check", "--phase", "design");
  assert.equal(text.code, 0);
  assert.equal(
    text.stdout,
    "check --phase design: 1 design, 1 contract, 0 data types, 1 invariant; 0 errors, 0 warnings. TypeScript 6.0.3 (bundled; the project's TypeScript 7.0.2 has no usable compiler API).\n",
  );
});

test("a TypeScript that Node finds outside the project's node_modules is not the project's", (t) => {
  const root = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-"));
  const elsewhere = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-global-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  t.after(() => fs.rmSync(elsewhere, { recursive: true, force: true }));
  fs.symlinkSync(path.join(repository, "node_modules/typescript-5"), path.join(elsewhere, "typescript"));

  // NODE_PATH is read when Node starts, so this needs a process of its own.
  const script = `import { loadTypeScript } from ${JSON.stringify(path.join(repository, "src/typescript.ts"))}; console.log(JSON.stringify(loadTypeScript(${JSON.stringify(root)}).info));`;
  const run = spawnSync(process.execPath, ["--input-type=module", "-e", script], { encoding: "utf8", env: { ...process.env, NODE_PATH: elsewhere } });
  assert.equal(run.stderr, "");
  assert.deepEqual(JSON.parse(run.stdout), { version: "6.0.3", source: "bundled" });
});

test("a project TypeScript that cannot be loaded does not stop the check", (t) => {
  const root = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-"));
  t.after(() => fs.rmSync(root, { recursive: true, force: true }));
  writeFile(root, "node_modules/typescript/package.json", JSON.stringify({ name: "typescript", version: "5.9.3", main: "index.js" }));
  writeFile(root, "node_modules/typescript/index.js", 'throw new Error("corrupted install");\n');

  assert.deepEqual(loadTypeScript(root).info, { version: "6.0.3", source: "bundled", fallbackReason: "the project's TypeScript cannot be loaded: corrupted install" });

  // An interrupted install: the package is there, its entry file is not. That is not "no TypeScript".
  const partial = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-"));
  t.after(() => fs.rmSync(partial, { recursive: true, force: true }));
  writeFile(partial, "node_modules/typescript/package.json", JSON.stringify({ name: "typescript", version: "5.9.3", main: "lib/typescript.js" }));
  assert.match(loadTypeScript(partial).info.fallbackReason ?? "", /^the project's TypeScript cannot be loaded: Cannot find module/);

  const odd = fs.mkdtempSync(path.join(fs.realpathSync(os.tmpdir()), "design-harness-"));
  t.after(() => fs.rmSync(odd, { recursive: true, force: true }));
  writeFile(odd, "node_modules/typescript/package.json", JSON.stringify({ name: "typescript", version: "5.9.3", main: "index.js" }));
  writeFile(odd, "node_modules/typescript/index.js", 'throw "boom";\n');
  assert.equal(loadTypeScript(odd).info.fallbackReason, "the project's TypeScript cannot be loaded: boom");
  // A configuration error is still reported as one, in the requested format.
  const { code, stdout, stderr } = cli(root, "check", "--phase", "design", "--format", "json", "--config", "nope.json");
  assert.equal(code, 2);
  assert.equal(stderr, "");
  assert.deepEqual(JSON.parse(stdout).diagnostics.map((diagnostic: { code: string }) => diagnostic.code), ["E_CONFIG"]);
});
