import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { test } from "node:test";
import { defaultConfig } from "../src/config.ts";
import { discoverDesigns, discoverSources, findFiles } from "../src/discovery.ts";
import { CAMPAIGNS, copyFixture, designProject, generated, MAIL, QUOTA, readFile, writeFile } from "./helpers.ts";

const design = (root: string, file: string) => writeFile(root, file, readFile(root, MAIL));

test("finds designs in dot-directories, sorted, with their module and generated path", (t) => {
  const root = copyFixture(t, "vertical");
  assert.deepEqual(discoverDesigns(root, defaultConfig), [
    { moduleId: "src/modules/campaigns", sourceFile: path.join(root, CAMPAIGNS), generatedFile: path.join(root, generated(CAMPAIGNS)) },
    { moduleId: "src/modules/mail", sourceFile: path.join(root, MAIL), generatedFile: path.join(root, generated(MAIL)) },
    { moduleId: "src/modules/quota", sourceFile: path.join(root, QUOTA), generatedFile: path.join(root, generated(QUOTA)) },
  ]);
});

test("a parent module and a nested module are two modules, each found once", (t) => {
  const root = copyFixture(t, "vertical");
  design(root, "src/.design/design.mdx");
  design(root, "src/modules/quota/limits/.design/design.mdx");
  design(root, ".design/design.mdx");

  const config = { ...defaultConfig, designs: ["**/.design/design.mdx", "src/**/.design/design.mdx"] };
  assert.deepEqual(
    discoverDesigns(root, config).map((found) => found.moduleId),
    [".", "src", "src/modules/campaigns", "src/modules/mail", "src/modules/quota", "src/modules/quota/limits"],
  );
  // The default pattern does not reach the project root.
  assert.ok(!discoverDesigns(root, defaultConfig).some((found) => found.moduleId === "."));
});

test("only .design/design.mdx is a design, whatever else the patterns match", (t) => {
  const root = copyFixture(t, "vertical");
  writeFile(root, generated(QUOTA), "// @generated by design; DO NOT EDIT.\n// Source: design.mdx\n");
  writeFile(root, "src/modules/quota/.design/notes.mdx", "# Notes");
  writeFile(root, "src/modules/quota/docs/design.mdx", "# Not a module marker");

  const config = { ...defaultConfig, designs: ["src/**/.design/*", "src/**/*.mdx"] };
  assert.deepEqual(
    discoverDesigns(root, config).map((found) => found.moduleId),
    ["src/modules/campaigns", "src/modules/mail", "src/modules/quota"],
  );
});

test("exclude patterns remove designs; a configured list replaces the default one", (t) => {
  const root = copyFixture(t, "vertical");
  design(root, "src/node_modules/pkg/.design/design.mdx");
  design(root, "src/dist/.design/design.mdx");

  const modules = (exclude: string[]) => discoverDesigns(root, { ...defaultConfig, exclude }).map((found) => found.moduleId);
  assert.deepEqual(modules(defaultConfig.exclude), ["src/modules/campaigns", "src/modules/mail", "src/modules/quota"]);
  assert.deepEqual(modules(["**/mail/**", "**/node_modules/**"]), ["src/dist", "src/modules/campaigns", "src/modules/quota"]);
  assert.deepEqual(modules(["src/modules/*/.design/design.mdx"]), ["src/dist", "src/node_modules/pkg"]);
});

test("symbolic links are not followed, inside or outside the project", (t) => {
  const root = copyFixture(t, "vertical");
  const outside = fs.mkdtempSync(path.join(os.tmpdir(), "design-harness-outside-"));
  t.after(() => fs.rmSync(outside, { recursive: true, force: true }));
  design(root, "elsewhere/.design/design.mdx");
  fs.cpSync(path.join(root, "elsewhere"), path.join(outside, "module"), { recursive: true });

  fs.symlinkSync(path.join(outside, "module"), path.join(root, "src/modules/outside"));
  fs.symlinkSync(path.join(root, "elsewhere"), path.join(root, "src/modules/inside"));
  fs.mkdirSync(path.join(root, "src/modules/linked/.design"), { recursive: true });
  fs.symlinkSync(path.join(root, MAIL), path.join(root, "src/modules/linked/.design/design.mdx"));

  assert.deepEqual(
    discoverDesigns(root, defaultConfig).map((found) => found.moduleId),
    ["src/modules/campaigns", "src/modules/mail", "src/modules/quota"],
  );
});

test("sources are .ts files: tests are not implementations, and design directories and declaration files are neither", (t) => {
  const root = designProject(t, {}, {
    "src/a.ts": "",
    "src/a.test.ts": "",
    "src/types.d.ts": "",
    "src/view.tsx": "",
    "src/esm.mts": "",
    "src/NOTES.md": "@implements Store",
    "src/m/.design/helper.ts": "",
    "tests/b.test.ts": "",
    "tests/helper.ts": "",
  });
  assert.deepEqual(discoverSources(root, { ...defaultConfig, implementations: ["src/**/*", "src/**/.design/*"], tests: ["src/**/*.test.*", "tests/**/*"] }), {
    implementations: ["src/a.ts"],
    tests: ["src/a.test.ts", "tests/b.test.ts", "tests/helper.ts"],
  });
});

test("findFiles walks only where a pattern can match", (t) => {
  const root = designProject(t, {});
  writeFile(root, "src/a.ts", "");
  writeFile(root, "src/deep/b.test.ts", "");
  writeFile(root, "tests/c.test.ts", "");
  writeFile(root, "scripts/d.ts", "");
  // A pattern that cannot be split into path segments is still matched, by walking everything.
  assert.deepEqual(findFiles(root, ["src/{deep/b,a}*.ts"], []), ["src/a.ts", "src/deep/b.test.ts"]);

  // Unreadable, and outside every pattern: never opened.
  fs.mkdirSync(path.join(root, "private"), { mode: 0o000 });
  try {
    assert.deepEqual(findFiles(root, ["src/**/*.ts"], ["**/*.test.ts"]), ["src/a.ts"]);
    assert.deepEqual(findFiles(root, ["src/**/*.test.ts", "tests/**/*.test.ts", "missing/**/*.ts"], []), ["src/deep/b.test.ts", "tests/c.test.ts"]);
    assert.deepEqual(findFiles(root, ["./tsconfig.json", "src/*.ts"], ["./tests/**"]), ["src/a.ts", "tsconfig.json"]);
    assert.deepEqual(findFiles(root, ["src/deep/**", "scripts/**"], []), ["scripts/d.ts", "src/deep/b.test.ts"]);
    assert.deepEqual(findFiles(root, ["{src,tests}/**/*.test.ts"], ["**/deep/**"]), ["tests/c.test.ts"]);
  } finally {
    fs.chmodSync(path.join(root, "private"), 0o700);
  }
});
