import assert from "node:assert/strict";
import { test } from "node:test";
import { buildGeneratedModule, extractBlock, GENERATED_HEADER, toSourceOffset } from "../src/extraction.ts";
import { parseDesignMdx } from "../src/mdx.ts";
import { doc } from "./helpers.ts";

const extract = (source: string) => buildGeneratedModule(parseDesignMdx(source, "design.mdx").blocks);

test("joins design blocks under the ownership header", () => {
  const source = doc(
    "# Title",
    "",
    "```ts design",
    "",
    "  export type A = string;",
    "",
    "",
    "```",
    "",
    "Prose between blocks.",
    "",
    "```ts design",
    "export type B = A;",
    "```",
  );
  assert.equal(
    extract(source).text,
    "// @generated by design; DO NOT EDIT.\n// Source: design.mdx\n\n\n  export type A = string;\n\nexport type B = A;\n",
  );
});

test("normalizes CRLF and maps every copied character back to the MDX source", () => {
  const source = [
    "# Заголовок 🙂",
    "",
    "```ts design",
    "/** Опис із апострофом ’ та 🙂. */",
    "export type A = string;",
    "```",
    "",
    "Проза.",
    "",
    "```ts design",
    "",
    "export interface B { a: A }",
    "```",
    "",
  ].join("\r\n");
  const { blocks } = parseDesignMdx(source, "design.mdx");
  const module = buildGeneratedModule(blocks);
  assert.ok(!module.text.includes("\r"));

  const firstBlock = GENERATED_HEADER.length + 1;
  const separator = firstBlock + extractBlock(blocks[0]).text.length + 1;
  let mapped = 0;
  for (let offset = 0; offset < module.text.length; offset++) {
    const sourceOffset = toSourceOffset(module, offset);
    if (sourceOffset === undefined) continue;
    mapped++;
    const char = module.text[offset];
    assert.equal(source[sourceOffset], char === "\n" ? "\r" : char, `generated offset ${offset}`);
  }
  // Every block character plus the line end after each block's last line.
  assert.equal(mapped, blocks.reduce((sum, block) => sum + extractBlock(block).text.length + 1, 0));

  assert.equal(toSourceOffset(module, 0), undefined, "header");
  assert.equal(toSourceOffset(module, firstBlock - 1), undefined, "empty line after the header");
  assert.equal(toSourceOffset(module, separator), undefined, "empty line between blocks");
  // The end of the text is where the compiler reports an unclosed declaration.
  assert.equal(toSourceOffset(module, module.text.length), source.indexOf("export interface B { a: A }") + "export interface B { a: A }".length);
});

test("a block on its own maps like the same block inside the module", () => {
  const source = doc("# Title", "", "```ts design", "export type A = string;", "```", "", "```ts design", "export type B =", "  A;", "```");
  const { blocks } = parseDesignMdx(source, "design.mdx");
  const block = extractBlock(blocks[1]);
  assert.equal(block.text, "export type B =\n  A;");
  assert.equal(toSourceOffset(block, 0), source.indexOf("export type B"));
  assert.equal(toSourceOffset(block, block.text.indexOf("A;")), source.indexOf("  A;") + 2);
  assert.equal(toSourceOffset(block, block.text.length), source.indexOf("  A;") + "  A;".length);
});

test("prose edits and block moves do not change the generated text", () => {
  const before = doc("# Quota", "", "Intro.", "", "```ts design", "export type A = string;", "```");
  const after = doc("# Quota, renamed", "", "```ts design", "export type A = string;", "```", "", "Intro moved and rewritten.");
  assert.equal(extract(after).text, extract(before).text);
  assert.notDeepEqual(extract(after).segments, extract(before).segments);
});
