import assert from "node:assert/strict";
import { test } from "node:test";
import { buildGeneratedModule, extractBlock, generatedHeader, toSourceOffset } from "../src/extraction.ts";
import { parseDesignMdx } from "../src/mdx.ts";
import { doc } from "./helpers.ts";

const extract = (source: string) => buildGeneratedModule([{ name: "m.cage.mdx", blocks: parseDesignMdx(source, "m.cage.mdx").blocks }]);

test("joins design blocks under the ownership header", () => {
  const source = doc(
    "# Title",
    "",
    "```ts design",
    "",
    "  export type A = string;",
    "",
    "",
    "```",
    "",
    "Prose between blocks.",
    "",
    "```ts design",
    "export type B = A;",
    "```",
  );
  assert.equal(
    extract(source).text,
    "// @generated by cage; DO NOT EDIT.\n// Source: m.cage.mdx\n\n\n  export type A = string;\n\nexport type B = A;\n",
  );
});

test("normalizes CRLF and maps every copied character back to the MDX source", () => {
  const source = [
    "# Заголовок 🙂",
    "",
    "```ts design",
    "/** Опис із апострофом ’ та 🙂. */",
    "export type A = string;",
    "```",
    "",
    "Проза.",
    "",
    "```ts design",
    "",
    "export interface B { a: A }",
    "```",
    "",
  ].join("\r\n");
  const { blocks } = parseDesignMdx(source, "m.cage.mdx");
  const module = buildGeneratedModule([{ name: "m.cage.mdx", blocks }]);
  assert.ok(!module.text.includes("\r"));

  const firstBlock = generatedHeader(["m.cage.mdx"]).length + 1;
  const separator = firstBlock + extractBlock(blocks[0], 0).text.length + 1;
  let mapped = 0;
  for (let offset = 0; offset < module.text.length; offset++) {
    const mappedTo = toSourceOffset(module, offset);
    if (mappedTo === undefined) continue;
    mapped++;
    assert.equal(mappedTo.document, 0);
    const char = module.text[offset];
    assert.equal(source[mappedTo.offset], char === "\n" ? "\r" : char, `generated offset ${offset}`);
  }
  // Every block character plus the line end after each block's last line.
  assert.equal(mapped, blocks.reduce((sum, block) => sum + extractBlock(block, 0).text.length + 1, 0));

  assert.equal(toSourceOffset(module, 0), undefined, "header");
  assert.equal(toSourceOffset(module, firstBlock - 1), undefined, "empty line after the header");
  assert.equal(toSourceOffset(module, separator), undefined, "empty line between blocks");
  // The end of the text is where the compiler reports an unclosed declaration.
  assert.deepEqual(toSourceOffset(module, module.text.length), { document: 0, offset: source.indexOf("export interface B { a: A }") + "export interface B { a: A }".length });
});

test("a block on its own maps like the same block inside the module", () => {
  const source = doc("# Title", "", "```ts design", "export type A = string;", "```", "", "```ts design", "export type B =", "  A;", "```");
  const { blocks } = parseDesignMdx(source, "m.cage.mdx");
  const block = extractBlock(blocks[1], 3);
  assert.equal(block.text, "export type B =\n  A;");
  assert.deepEqual(toSourceOffset(block, 0), { document: 3, offset: source.indexOf("export type B") });
  assert.deepEqual(toSourceOffset(block, block.text.indexOf("A;")), { document: 3, offset: source.indexOf("  A;") + 2 });
  assert.deepEqual(toSourceOffset(block, block.text.length), { document: 3, offset: source.indexOf("  A;") + "  A;".length });
});

test("prose edits and block moves do not change the generated text", () => {
  const before = doc("# Quota", "", "Intro.", "", "```ts design", "export type A = string;", "```");
  const after = doc("# Quota, renamed", "", "```ts design", "export type A = string;", "```", "", "Intro moved and rewritten.");
  assert.equal(extract(after).text, extract(before).text);
  assert.notDeepEqual(extract(after).segments, extract(before).segments);
});

test("the blocks of several documents make one module, in document order, and map back to their own document", () => {
  const first = parseDesignMdx(doc("# Перший", "", "```ts design", "export type A = string;", "```"), "a.cage.mdx");
  const second = parseDesignMdx(doc("# Другий", "", "```ts design", "export type B = A;", "```", "", "```ts design", "export type C = B;", "```"), "b.cage.mdx");
  const module = buildGeneratedModule([
    { name: "a.cage.mdx", blocks: first.blocks },
    { name: "b.cage.mdx", blocks: second.blocks },
  ]);
  assert.equal(module.text, "// @generated by cage; DO NOT EDIT.\n// Source: a.cage.mdx, b.cage.mdx\n\nexport type A = string;\n\nexport type B = A;\n\nexport type C = B;\n");
  assert.equal(module.blockStarts.length, 3);
  assert.deepEqual(toSourceOffset(module, module.text.indexOf("type A")), { document: 0, offset: "# Перший\n\n```ts design\nexport ".length });
  assert.deepEqual(toSourceOffset(module, module.text.indexOf("type C")), { document: 1, offset: "# Другий\n\n```ts design\nexport type B = A;\n```\n\n```ts design\nexport ".length });
});
