import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { test, type TestContext } from "node:test";
import type { ExtractReport } from "../src/extract.ts";
import { CAMPAIGNS, cli, copyFixture, editFile, find, generated, isError, MAIL, QUOTA, readFile, senderWarning, snapshot, writeFile } from "./helpers.ts";

const OUTPUTS = [CAMPAIGNS, MAIL, QUOTA].map(generated);

function extract(root: string, ...args: string[]): { code: number; report: ExtractReport } {
  const { code, stdout, stderr } = cli(root, "extract", "--format", "json", ...args);
  assert.equal(stderr, "");
  return { code, report: JSON.parse(stdout) };
}

const statuses = (report: ExtractReport) => Object.fromEntries(report.outputs.map((output) => [output.path, output.status]));
/** Errors only: the plan fixture always carries one warning, for the contract without invariants. */
const codes = (report: ExtractReport) => report.diagnostics.filter(isError).map(({ code, file }) => ({ code, file }));
const SENDER_WARNING = senderWarning();

/** A fixture copy whose generated files are already written. */
function extracted(t: TestContext): string {
  const root = copyFixture(t, "vertical");
  assert.equal(extract(root).code, 0);
  return root;
}

test("extract writes one generated file per design and nothing else", (t) => {
  const root = copyFixture(t, "vertical");
  const before = snapshot(root);

  const { code, report } = extract(root);
  assert.equal(code, 0);
  assert.deepEqual(
    { ...report, diagnostics: report.diagnostics.map((diagnostic) => diagnostic.code) },
    {
      schemaVersion: 1,
      command: "extract",
      checkOnly: false,
      generatedFiles: true,
      ok: true,
      outputs: [
        { sources: [CAMPAIGNS], path: generated(CAMPAIGNS), status: "written" },
        { sources: [MAIL], path: generated(MAIL), status: "written" },
        { sources: [QUOTA], path: generated(QUOTA), status: "written" },
      ],
      diagnostics: ["W_NO_INVARIANTS"],
    },
  );

  const after = snapshot(root);
  assert.deepEqual(Object.keys(after).filter((file) => !(file in before)), OUTPUTS);
  for (const file of Object.keys(before)) assert.equal(after[file], before[file], file);
  assert.equal(
    after[generated(QUOTA)],
    [
      "// @generated by cage; DO NOT EDIT.",
      "// Source: quota.cage.mdx",
      "",
      "/**",
      " * @data",
      " * @description Ідентифікатор акаунта для обліку квоти.",
      " */",
      "export type AccountId = string;",
      "",
      "/**",
      " * @contract",
      " * @description Обліковує доступні спроби окремо для кожного акаунта.",
      " * @invariant accounts Використання квоти одного акаунта не змінює квоту іншого.",
      " */",
      "export interface Quota {",
      "  /**",
      "   * @description Намагається використати одну одиницю доступної квоти.",
      "   * @invariant empty Для невідомого акаунта або нульового залишку повертає false без списання.",
      "   * @invariant consume За додатного залишку повертає true та зменшує залишок на один.",
      "   * @invariant race Паралельні виклики не можуть використати більше доступного залишку.",
      "   */",
      "  take(accountId: AccountId): Promise<boolean>;",
      "}",
      "",
    ].join("\n"),
  );
});

test("a repeated extract rewrites nothing, and --check passes", (t) => {
  const root = extracted(t);
  const identity = () => OUTPUTS.map((file) => fs.statSync(path.join(root, file), { bigint: true })).map(({ ino, mtimeNs }) => [ino, mtimeNs]);
  const before = identity();

  const again = extract(root);
  assert.equal(again.code, 0);
  assert.deepEqual(Object.values(statuses(again.report)), ["unchanged", "unchanged", "unchanged"]);
  assert.deepEqual(identity(), before);

  const check = extract(root, "--check");
  assert.equal(check.code, 0);
  assert.equal(check.report.checkOnly, true);
  assert.equal(check.report.ok, true);
  assert.deepEqual(Object.values(statuses(check.report)), ["unchanged", "unchanged", "unchanged"]);
});

test("--check reports missing outputs and writes nothing", (t) => {
  const root = copyFixture(t, "vertical");
  const before = snapshot(root);

  const { code, report } = extract(root, "--check");
  assert.equal(code, 1);
  assert.equal(report.ok, false);
  assert.deepEqual(Object.values(statuses(report)), ["missing", "missing", "missing"]);
  assert.deepEqual(codes(report), OUTPUTS.map((file) => ({ code: "E_GENERATED_MISSING", file })));
  assert.deepEqual(report.diagnostics.find(isError)!.related, [{ message: "A design document it is generated from.", file: CAMPAIGNS }]);
  assert.deepEqual(snapshot(root), before);
});

test("a contract change makes the output stale until the next extract; a prose change does not", (t) => {
  const root = extracted(t);

  editFile(root, QUOTA, (s) => s.replace("# Квота", "# Квота акаунта").replace("## Типи", "Новий абзац про облік.\n\n## Типи"));
  assert.equal(extract(root, "--check").code, 0);

  editFile(root, QUOTA, (s) => s.replace("export type AccountId = string;", "export type AccountId = string | number;"));
  const stale = extract(root, "--check");
  assert.equal(stale.code, 1);
  assert.deepEqual(statuses(stale.report), { [generated(CAMPAIGNS)]: "unchanged", [generated(MAIL)]: "unchanged", [generated(QUOTA)]: "stale" });
  assert.deepEqual(codes(stale.report), [{ code: "E_GENERATED_STALE", file: generated(QUOTA) }]);
  assert.ok(!readFile(root, generated(QUOTA)).includes("string | number"));

  const fixed = extract(root);
  assert.equal(fixed.code, 0);
  assert.deepEqual(statuses(fixed.report), { [generated(CAMPAIGNS)]: "unchanged", [generated(MAIL)]: "unchanged", [generated(QUOTA)]: "written" });
  assert.ok(readFile(root, generated(QUOTA)).includes("string | number"));
  assert.equal(extract(root, "--check").code, 0);
});

test("a generated file edited by hand is stale, and extract restores it from the MDX", (t) => {
  const root = extracted(t);
  const original = readFile(root, generated(MAIL));
  writeFile(root, generated(MAIL), original.replace("Promise<void>", "Promise<number>"));

  const check = extract(root, "--check");
  assert.equal(check.code, 1);
  assert.deepEqual(codes(check.report), [{ code: "E_GENERATED_STALE", file: generated(MAIL) }]);

  assert.equal(extract(root).code, 0);
  assert.equal(readFile(root, generated(MAIL)), original);
});

test("an output that differs only in line endings is current", (t) => {
  const root = extracted(t);
  const crlf = readFile(root, generated(MAIL)).replaceAll("\n", "\r\n");
  writeFile(root, generated(MAIL), crlf);

  assert.equal(extract(root, "--check").code, 0);
  assert.equal(statuses(extract(root).report)[generated(MAIL)], "unchanged");
  assert.equal(readFile(root, generated(MAIL)), crlf);
});

test("a file without the ownership header is never overwritten, and blocks all writing", (t) => {
  const root = copyFixture(t, "vertical");
  const foreign = "export interface Sender { send(text: string): void }\n";
  writeFile(root, generated(MAIL), foreign);
  const before = snapshot(root);

  for (const args of [[], ["--check"]]) {
    const { code, report } = extract(root, ...args);
    assert.equal(code, 1);
    assert.deepEqual(statuses(report), { [generated(CAMPAIGNS)]: "missing", [generated(MAIL)]: "conflict", [generated(QUOTA)]: "missing" });
    assert.ok(codes(report).some(({ code, file }) => code === "E_GENERATED_CONFLICT" && file === generated(MAIL)));
    assert.deepEqual(snapshot(root), before);
  }
  // Without --check the other outputs are not errors: they were only not written.
  assert.deepEqual(codes(extract(root).report), [{ code: "E_GENERATED_CONFLICT", file: generated(MAIL) }]);
});

test("writing never goes through a symbolic link", (t) => {
  const root = copyFixture(t, "vertical");
  const target = path.join(root, "elsewhere.ts");
  fs.writeFileSync(target, "// @generated by cage; DO NOT EDIT.\n// Source: mail.cage.mdx\n");
  fs.mkdirSync(path.dirname(path.join(root, generated(MAIL))), { recursive: true });
  fs.symlinkSync(target, path.join(root, generated(MAIL)));

  const { code, report } = extract(root);
  assert.equal(code, 1);
  assert.equal(statuses(report)[generated(MAIL)], "conflict");
  assert.equal(fs.readFileSync(target, "utf8"), "// @generated by cage; DO NOT EDIT.\n// Source: mail.cage.mdx\n");
  assert.ok(fs.lstatSync(path.join(root, generated(MAIL))).isSymbolicLink());
});

test("a design error in any module means no output is written", (t) => {
  const root = extracted(t);
  editFile(root, QUOTA, (s) => s.replace("export type AccountId = string;", "export type AccountId = string | number;"));
  editFile(root, MAIL, (s) => s.replace("send(text: string)", "send(text: Txt)"));
  const before = snapshot(root);

  for (const args of [[], ["--check"]]) {
    const { code, report } = extract(root, ...args);
    assert.equal(code, 1);
    assert.equal(report.ok, false);
    assert.deepEqual(report.outputs, []);
    assert.deepEqual(codes(report), [{ code: "E_TYPESCRIPT", file: MAIL }]);
    assert.deepEqual(snapshot(root), before);
  }
});

test("a write failure is exit 2, with every output marked written or failed", { skip: process.getuid?.() === 0 }, (t) => {
  const root = copyFixture(t, "vertical");
  const locked = path.join(root, path.dirname(MAIL));
  fs.chmodSync(locked, 0o555);
  try {
    const { code, report } = extract(root);
    assert.equal(code, 2);
    assert.equal(report.ok, false);
    assert.deepEqual(statuses(report), { [generated(CAMPAIGNS)]: "written", [generated(MAIL)]: "failed", [generated(QUOTA)]: "written" });
    assert.match(report.outputs[1].error!, /^EACCES/);
    assert.deepEqual(codes(report), [{ code: "E_ENVIRONMENT", file: generated(MAIL) }]);
    assert.deepEqual(fs.readdirSync(locked).sort(), ["callback-sender.ts", "mail.cage.mdx"]);
  } finally {
    fs.chmodSync(locked, 0o755);
  }
});

test("after a design document is deleted its generated file is neither a source nor removed", (t) => {
  const root = extracted(t);
  fs.rmSync(path.join(root, CAMPAIGNS));
  const orphan = readFile(root, generated(CAMPAIGNS));

  const { code, report } = extract(root);
  assert.equal(code, 0);
  assert.deepEqual(Object.keys(statuses(report)), [generated(MAIL), generated(QUOTA)]);
  assert.equal(readFile(root, generated(CAMPAIGNS)), orphan);
});

test("an empty scope is an error, not an empty success", (t) => {
  const root = copyFixture(t, "vertical");
  fs.rmSync(path.join(root, "src"), { recursive: true });
  for (const args of [[], ["--check"]]) {
    const { code, report } = extract(root, ...args);
    assert.equal(code, 1);
    assert.equal(report.ok, false);
    assert.deepEqual(codes(report), [{ code: "E_NO_DESIGNS", file: undefined }]);
  }
});

test("configuration and environment problems are exit 2", (t) => {
  const root = copyFixture(t, "vertical");

  const missingConfig = extract(root, "--config", "nope.json");
  assert.equal(missingConfig.code, 2);
  assert.deepEqual(codes(missingConfig.report), [{ code: "E_CONFIG", file: "nope.json" }]);

  writeFile(root, ".cage/config.json", '{ "version": 1, "output": "generated" }');
  const invalidConfig = extract(root);
  assert.equal(invalidConfig.code, 2);
  assert.deepEqual(codes(invalidConfig.report), [{ code: "E_CONFIG", file: ".cage/config.json" }]);

  writeFile(root, ".cage/config.json", '{ "version": 1, "tsconfig": "tsconfig.missing.json" }');
  const missingTsconfig = extract(root);
  assert.equal(missingTsconfig.code, 2);
  assert.deepEqual(codes(missingTsconfig.report), [{ code: "E_ENVIRONMENT", file: "tsconfig.missing.json" }]);
  assert.deepEqual(Object.keys(snapshot(root)).filter((file) => file.endsWith(".generated.ts")), []);
});

test("the configuration selects the scope", (t) => {
  const root = copyFixture(t, "vertical");
  writeFile(root, "tools/design.json", JSON.stringify({ version: 1, exclude: ["**/campaigns/**"] }));

  const { code, report } = extract(root, "--config", "tools/design.json");
  assert.equal(code, 0);
  assert.deepEqual(Object.keys(statuses(report)), [generated(MAIL), generated(QUOTA)]);
});

test("with generated files turned off extract checks the designs and writes nothing", (t) => {
  const root = copyFixture(t, "vertical");
  writeFile(root, ".cage/config.json", JSON.stringify({ version: 1, generatedFiles: false }));
  const before = snapshot(root);

  const { code, report } = extract(root);
  assert.equal(code, 0);
  assert.equal(report.generatedFiles, false);
  assert.deepEqual(report.outputs, []);
  assert.deepEqual(snapshot(root), before);
  assert.equal(cli(root, "extract").stdout, `${SENDER_WARNING}\nextract: generated files are turned off in the configuration ("generatedFiles": false); nothing to write; 1 warning.\n`);
  assert.equal(extract(root, "--check").code, 0);

  // The designs are still checked.
  editFile(root, QUOTA, (s) => s.replace("take(accountId: AccountId)", "take(accountId: AccountIdd)"));
  const broken = extract(root);
  assert.equal(broken.code, 1);
  assert.deepEqual(codes(broken.report).map(({ code }) => code), ["E_TYPESCRIPT"]);
});

test("the text report lists outputs, diagnostics and a summary", (t) => {
  const root = copyFixture(t, "vertical");
  assert.equal(
    cli(root, "extract").stdout,
    [
      `written   ${generated(CAMPAIGNS)}`,
      `written   ${generated(MAIL)}`,
      `written   ${generated(QUOTA)}`,
      SENDER_WARNING,
      "extract: 3 written, 0 unchanged; 1 warning.",
      "",
    ].join("\n"),
  );
  assert.equal(cli(root, "extract", "--check").stdout.split("\n").at(-2), "extract --check: 3 generated files are current; 1 warning.");

  const broken = find(editFile(root, QUOTA, (s) => s.replace("take(accountId: AccountId)", "take(accountId: AccountIdd)")), "AccountIdd");
  const failed = cli(root, "extract");
  assert.equal(failed.code, 1);
  assert.equal(
    failed.stdout,
    [
      SENDER_WARNING,
      `${QUOTA}:${broken.line}:${broken.column}: error E_TYPESCRIPT TS2552: Cannot find name 'AccountIdd'. Did you mean 'AccountId'?`,
      "extract: 1 error, nothing written; 1 warning.",
      "",
    ].join("\n"),
  );

  editFile(root, QUOTA, (s) => s.replace("take(accountId: AccountIdd)", "take(accountId: AccountId | number)"));
  const stale = cli(root, "extract", "--check");
  assert.equal(stale.code, 1);
  assert.equal(
    stale.stdout,
    [
      `unchanged ${generated(CAMPAIGNS)}`,
      `unchanged ${generated(MAIL)}`,
      `stale     ${generated(QUOTA)}`,
      SENDER_WARNING,
      `${generated(QUOTA)}: error E_GENERATED_STALE: The generated file differs from its design documents. Run \`cage extract\`.`,
      `  ${QUOTA}: A design document it is generated from.`,
      "extract --check: 1 error; 1 warning.",
      "",
    ].join("\n"),
  );
});
