import { lastStartingAtOrBefore } from "./location.ts";
import type { BlockLine, DesignBlock } from "./mdx.ts";

/** The directory of a module that belongs to cage: its generated module and its ignore file. */
export const CAGE_DIRECTORY = ".cage";
export const GENERATED_FILE_NAME = "generated.ts";
/** The first line of every generated file; a file without it is not ours to overwrite. */
export const GENERATED_MARKER = "// @generated by cage; DO NOT EDIT.\n";

/** One copied line: `length` characters at `generatedStart` come from `sourceStart` in document `document`. */
export interface Segment {
  generatedStart: number;
  sourceStart: number;
  length: number;
  /** Index of the design document the line was copied from. */
  document: number;
}

/** TypeScript text assembled from design block lines, with its mapping back to the documents. */
export interface ExtractedText {
  text: string;
  /** Sorted by `generatedStart`; text that was not copied from a block has no segment. */
  segments: Segment[];
}

export interface GeneratedModule extends ExtractedText {
  /** Offset in `text` where each design block starts, in document order. */
  blockStarts: number[];
  /** Offset in `text` of each module specifier that was rewritten, to what the document says. */
  writtenSpecifiers: Map<number, string>;
}

/**
 * Text put into a line of the generated module that is not in the document:
 * the `../` that takes a relative specifier from the document's directory to
 * `.cage/` below it. `line` and `column` are within the block.
 */
export interface Insert {
  line: number;
  column: number;
  text: string;
  /** The specifier as the document writes it, for messages. */
  original: string;
}

/** The blocks of one document of a module, with the name the header lists and what to insert into each block. */
export interface DocumentBlocks {
  name: string;
  blocks: readonly DesignBlock[];
  /** By index in `blocks`. */
  inserts?: ReadonlyMap<number, readonly Insert[]>;
}

/** The ownership marker, then the documents the module was assembled from. */
export const generatedHeader = (names: readonly string[]) => `${GENERATED_MARKER}// Source: ${names.join(", ")}\n`;

/** The generated module: ownership header, an empty line, then the blocks of every document separated by an empty line. */
export function buildGeneratedModule(documents: readonly DocumentBlocks[]): GeneratedModule {
  const module: GeneratedModule = { text: `${generatedHeader(documents.map((document) => document.name))}\n`, segments: [], blockStarts: [], writtenSpecifiers: new Map() };
  documents.forEach((document, index) => {
    document.blocks.forEach((block, order) => {
      if (module.blockStarts.length > 0) module.text += "\n\n";
      module.blockStarts.push(module.text.length);
      appendLines(module, block.lines, index, document.inserts?.get(order) ?? [], module.writtenSpecifiers);
    });
  });
  module.text += "\n";
  return module;
}

/** Index of the block that holds an offset of the generated text; the header counts as the first block. */
export function blockAt(module: GeneratedModule, offset: number): number {
  return lastStartingAtOrBefore(module.blockStarts, (start) => start, offset);
}

/** One block on its own, used to check that it is syntactically complete. */
export function extractBlock(block: DesignBlock, document: number): ExtractedText {
  const extracted: ExtractedText = { text: "", segments: [] };
  appendLines(extracted, block.lines, document);
  return extracted;
}

function appendLines(target: ExtractedText, lines: readonly BlockLine[], document: number, inserts: readonly Insert[] = [], written?: Map<number, string>): void {
  lines.forEach((line, index) => {
    if (index > 0) target.text += "\n";
    let column = 0;
    // An insert splits the line: what surrounds it maps to the document, the insert itself maps nowhere.
    for (const insert of inserts.filter((candidate) => candidate.line === index).sort((a, b) => a.column - b.column)) {
      const before = line.text.slice(column, insert.column);
      if (before.length > 0) target.segments.push({ generatedStart: target.text.length, sourceStart: line.sourceStart + column, length: before.length, document });
      target.text += before;
      // The specifier's opening quote is the character before the insert.
      written?.set(target.text.length - 1, insert.original);
      target.text += insert.text;
      column = insert.column;
    }
    const rest = line.text.slice(column);
    target.segments.push({ generatedStart: target.text.length, sourceStart: line.sourceStart + column, length: rest.length, document });
    target.text += rest;
  });
}

/**
 * Maps an offset in extracted text to a document and an offset in it. The
 * end of a copied line, and the end of the text, map to the end of the
 * authored line. Header and separator offsets have no authored position and
 * return undefined.
 */
export function toSourceOffset(extracted: ExtractedText, offset: number): { document: number; offset: number } | undefined {
  const { text, segments } = extracted;
  const last = segments.at(-1);
  if (!last) return undefined;
  if (offset === text.length) return { document: last.document, offset: last.sourceStart + last.length };
  const segment = segments[lastStartingAtOrBefore(segments, (item) => item.generatedStart, offset)];
  if (offset < segment.generatedStart || offset > segment.generatedStart + segment.length) return undefined;
  return { document: segment.document, offset: segment.sourceStart + (offset - segment.generatedStart) };
}
