import path from "node:path";
import { lastStartingAtOrBefore } from "./location.ts";
import type { BlockLine, DesignBlock } from "./mdx.ts";

export const GENERATED_FILE_NAME = "design.generated.ts";
export const GENERATED_HEADER = "// @generated by design; DO NOT EDIT.\n// Source: design.mdx\n";

/** One copied line: `length` characters at `generatedStart` come from `sourceStart` in the MDX. */
export interface Segment {
  generatedStart: number;
  sourceStart: number;
  length: number;
}

/** TypeScript text assembled from design block lines, with its mapping back to the MDX. */
export interface ExtractedText {
  text: string;
  /** Sorted by `generatedStart`; text that was not copied from a block has no segment. */
  segments: Segment[];
}

export function generatedPathFor(mdxFile: string): string {
  return path.join(path.dirname(mdxFile), GENERATED_FILE_NAME);
}

/** The generated module: ownership header, an empty line, then the blocks separated by an empty line. */
export function buildGeneratedModule(blocks: readonly DesignBlock[]): ExtractedText {
  const module: ExtractedText = { text: `${GENERATED_HEADER}\n`, segments: [] };
  blocks.forEach((block, index) => {
    if (index > 0) module.text += "\n\n";
    appendLines(module, block.lines);
  });
  module.text += "\n";
  return module;
}

/** One block on its own, used to check that it is syntactically complete. */
export function extractBlock(block: DesignBlock): ExtractedText {
  const extracted: ExtractedText = { text: "", segments: [] };
  appendLines(extracted, block.lines);
  return extracted;
}

function appendLines(target: ExtractedText, lines: readonly BlockLine[]): void {
  lines.forEach((line, index) => {
    if (index > 0) target.text += "\n";
    target.segments.push({ generatedStart: target.text.length, sourceStart: line.sourceStart, length: line.text.length });
    target.text += line.text;
  });
}

/**
 * Maps an offset in extracted text to the MDX source. The end of a copied
 * line, and the end of the text, map to the end of the authored line. Header
 * and separator offsets have no authored position and return undefined.
 */
export function toSourceOffset(extracted: ExtractedText, offset: number): number | undefined {
  const { text, segments } = extracted;
  const last = segments.at(-1);
  if (!last) return undefined;
  if (offset === text.length) return last.sourceStart + last.length;
  const segment = segments[lastStartingAtOrBefore(segments, (item) => item.generatedStart, offset)];
  if (offset < segment.generatedStart || offset > segment.generatedStart + segment.length) return undefined;
  return segment.sourceStart + (offset - segment.generatedStart);
}
