import fs from "node:fs";
import path from "node:path";
import type { Diagnostic } from "./diagnostic.ts";
import { GENERATED_MARKER } from "./extraction.ts";
import { stripBom } from "./location.ts";

export type OutputState = "current" | "missing" | "stale" | "conflict";

/**
 * Compares a generated file on disk with the text extracted from the current
 * MDX, ignoring CRLF/LF differences. A path that is not a regular file that
 * starts with the ownership header is not ours to write: "conflict".
 */
export function inspectOutput(file: string, expected: string): OutputState {
  let stats: fs.Stats;
  try {
    stats = fs.lstatSync(file);
  } catch (cause) {
    if ((cause as NodeJS.ErrnoException).code === "ENOENT") return "missing";
    throw cause;
  }
  // A symbolic link or a directory: writing must not pass through it.
  if (!stats.isFile()) return "conflict";
  const text = stripBom(fs.readFileSync(file, "utf8")).replaceAll("\r\n", "\n");
  if (!text.startsWith(GENERATED_MARKER)) return "conflict";
  return text === expected ? "current" : "stale";
}

/** Replaces the file atomically: readers see the old or the new text, never a partial one. */
export function writeOutput(file: string, text: string): void {
  const temporary = `${file}.${process.pid}.tmp`;
  try {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(temporary, text, { flag: "wx" });
    fs.renameSync(temporary, file);
  } catch (cause) {
    fs.rmSync(temporary, { force: true });
    throw cause;
  }
}

const PROBLEMS: Readonly<Record<Exclude<OutputState, "current">, { code: string; message: string }>> = {
  missing: { code: "E_GENERATED_MISSING", message: "The generated file is missing. Run `cage extract`." },
  stale: { code: "E_GENERATED_STALE", message: "The generated file differs from its design documents. Run `cage extract`." },
  conflict: {
    code: "E_GENERATED_CONFLICT",
    message: "This path is not a file generated by cage (no ownership header, or not a regular file). It was not overwritten; move or delete it.",
  },
};

/** The diagnostic for a generated file that is not current. `file` and `sources` are project-relative paths. */
export function outputProblem(state: Exclude<OutputState, "current">, file: string, sources: readonly string[]): Diagnostic {
  return { ...PROBLEMS[state], severity: "error", file, related: sources.map((source) => ({ message: "A design document it is generated from.", file: source })) };
}
